### PR TITLE
Updating default Redirect URI

### PR DESCRIPTION
**Pull request by trwalke**
Changing redirect URI to https://login.microsoftonline.com/common/oauth2/nativeclient Via the new WithDefaultRedirectUri() method.

### CODE REVIEW

**Comment by jmprieur** [comment]
@trwalke . I'll merge the PR once the quickstart is updated in docs.ms:
https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-windows-desktop

Will you provide a PR for the quickstart?

**Comment by trwalke** [comment]
@jmprieur Yes, I will be updating the quick start as well

**Comment by jmprieur** [comment]
@trwalke : when you do update the qs, at mention me (otherwise I won't see it)

**Comment by jennyf19** [comment]
closing. fixed in a later PR

**Comment by jmprieur** [comment]
@jennyf19 : I guess we have the same in the B2C desktop sample?

**Comment by jennyf19** [comment]
@jmprieur yes, that's correct. will do, as i will need to make changes in the app reg as well.

**Pull request closed without merging**
