### PR TITLE
Updated note on gov cloud for graph endpoint

### PR DESCRIPTION
**Pull request by aiwangmicrosoft**

### CODE REVIEW

**Comment by aiwangmicrosoft** [comment]
next time, I'll skip the GUI and just put it all in one commit. :(

**Review by jmprieur — CHANGES_REQUESTED** [review]
Same comment as the previous. Please provide links to the national cloud section of the article where the user can find the link to the graph endpoints;

**Comment by aiwangmicrosoft** [comment]
Updated, @jmprieur or @trwalke to merge?

**Review by trwalke — APPROVED** [review]
Approval for when the link is added to the comment

**Review by jmprieur — APPROVED** [review]
LGTM. Thanks @aiwangmicrosoft

**Pull request merged**
